uncomment some more tests

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -51,47 +51,47 @@ jobs:
         # so we can reference files that wouldn't be copied in a temp sdist folder
         run: python -m build --wheel -v --config-setting=--build-option="build_ext --plat-name=${{matrix.plat-name}} build --plat-name=${{matrix.plat-name}} bdist_wheel --plat-name=${{matrix.plat-name}}"
 
-  # build_cygwin:
-  #   # Temporarily suppress warnings to focus on fixing errors
-  #   env:
-  #     CFLAGS : '-w'
-  #     CXXFLAGS : '-w'
-  #   runs-on: windows-2022
-  #   timeout-minutes: *timeout-minutes
-  #   defaults:
-  #     run:
-  #       # shell: C:\cygwin\bin\env.exe CYGWIN_NOWINPATH=1 CHERE_INVOKING=1 C:\cygwin\bin\bash.exe -o igncr -eo pipefail '{0}'
-  #       shell: bash -o igncr -eo pipefail '{0}'
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #     - uses: cygwin/cygwin-install-action@master
-  #       with:
-  #         platform: x86_64
-  #         # Note: No provided caches yet: https://github.com/cygwin/cygwin-install-action/pull/6
-  #         packages: >-
-  #           gcc-core
-  #           gcc-g++
-  #           python3-devel
-  #           python3-build
-  #           python3-tomli
-  #     - name: Debug python
-  #       run: |
-  #         python --version
-  #         python -c "import sysconfig; print(sysconfig.get_paths())"
-  #         ls -R /usr/include | grep Python.h || true
-  #     - name: Disable CRLF line endings in git checkout
-  #       run: git config --global core.autocrlf input
-  #     - name: Build and install
-  #       # We don't actually need wheels, but this causes a direct-from-source build,
-  #       # so we can reference files that wouldn't be copied in a temp sdist folder
-  #       run: python -m build --wheel -v
-  #     - uses: actions/upload-artifact@v4
-  #       # Upload artifacts even if tests fail
-  #       if: ${{ always() }}
-  #       with:
-  #         name: artifacts-cygwin
-  #         path: dist/*.whl
-  #         if-no-files-found: error
+  build_cygwin:
+    # Temporarily suppress warnings to focus on fixing errors
+    env:
+      CFLAGS : '-w'
+      CXXFLAGS : '-w'
+    runs-on: windows-2022
+    timeout-minutes: *timeout-minutes
+    defaults:
+      run:
+        # shell: C:\cygwin\bin\env.exe CYGWIN_NOWINPATH=1 CHERE_INVOKING=1 C:\cygwin\bin\bash.exe -o igncr -eo pipefail '{0}'
+        shell: bash -o igncr -eo pipefail '{0}'
+    steps:
+      - uses: actions/checkout@v4
+      - uses: cygwin/cygwin-install-action@master
+        with:
+          platform: x86_64
+          # Note: No provided caches yet: https://github.com/cygwin/cygwin-install-action/pull/6
+          packages: >-
+            gcc-core
+            gcc-g++
+            python3-devel
+            python3-build
+            python3-tomli
+      - name: Debug python
+        run: |
+          python --version
+          python -c "import sysconfig; print(sysconfig.get_paths())"
+          ls -R /usr/include | grep Python.h || true
+      - name: Disable CRLF line endings in git checkout
+        run: git config --global core.autocrlf input
+      - name: Build and install
+        # We don't actually need wheels, but this causes a direct-from-source build,
+        # so we can reference files that wouldn't be copied in a temp sdist folder
+        run: python -m build --wheel -v
+      - uses: actions/upload-artifact@v4
+        # Upload artifacts even if tests fail
+        if: ${{ always() }}
+        with:
+          name: artifacts-cygwin
+          path: dist/*.whl
+          if-no-files-found: error
 
   # test:
   #   name: Build and test
@@ -217,61 +217,62 @@ jobs:
   #       with:
   #         name: artifacts-*
 
-  # # This job can be run locally by running `pre-commit run`
-  # checkers:
-  #   runs-on: ubuntu-latest
-  #   timeout-minutes: *timeout-minutes
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #     - uses: astral-sh/setup-uv@v7
-  #       with:
-  #         # This job only needs to target the oldest supported version
-  #         python-version: "3.9"
-  #         activate-environment: true
-  #     - run: uv pip install --group=checkers
+  # This job can be run locally by running `pre-commit run`
+  checkers:
+    runs-on: ubuntu-latest
+    timeout-minutes: *timeout-minutes
+    steps:
+      - uses: actions/checkout@v4
+      - uses: astral-sh/setup-uv@v7
+        with:
+          # This job only needs to target the oldest supported version
+          python-version: "3.9"
+          activate-environment: true
+      - run: uv pip install --group=checkers
 
-  #     # !cancelled(): Show issues even if the previous steps failed. But still fail the job
-  #     - run: pycln . --config=pycln.toml --check
+      # !cancelled(): Show issues even if the previous steps failed. But still fail the job
+      - run: pycln . --config=pycln.toml --check
 
-  #     - name: Run Ruff linter
-  #       uses: astral-sh/ruff-action@v3
-  #       if: ${{ !cancelled() }}
-  #     - name: Run Ruff formatter
-  #       run: ruff format --check
-  #       if: ${{ !cancelled() }}
+      - name: Run Ruff linter
+        uses: astral-sh/ruff-action@v3
+        if: ${{ !cancelled() }}
+      - name: Run Ruff formatter
+        run: ruff format --check
+        if: ${{ !cancelled() }}
 
-  #     # Too many files to fit in a single command, also exclude vendored Scintilla and MAPIStubLibrary
-  #     - run: |
-  #         clang-format --Werror --dry-run $(git ls-files '*.cpp' ':!:com/win32comext/mapi/src/MAPIStubLibrary/')
-  #         if ($LastExitCode -ne 0) { exit $LastExitCode }
-  #       shell: pwsh
-  #       if: ${{ !cancelled() }}
-  #     - run: |
-  #         clang-format --Werror --dry-run $(git ls-files '*.h' ':!:Pythonwin/Scintilla/' ':!:com/win32comext/mapi/src/MAPIStubLibrary/')
-  #         if ($LastExitCode -ne 0) { exit $LastExitCode }
-  #       shell: pwsh
-  #       if: ${{ !cancelled() }}
+      # Too many files to fit in a single command, also exclude vendored Scintilla and MAPIStubLibrary
+      - run: |
+          clang-format --Werror --dry-run $(git ls-files '*.cpp' ':!:com/win32comext/mapi/src/MAPIStubLibrary/')
+          if ($LastExitCode -ne 0) { exit $LastExitCode }
+        shell: pwsh
+        if: ${{ !cancelled() }}
+      - run: |
+          clang-format --Werror --dry-run $(git ls-files '*.h' ':!:Pythonwin/Scintilla/' ':!:com/win32comext/mapi/src/MAPIStubLibrary/')
+          if ($LastExitCode -ne 0) { exit $LastExitCode }
+        shell: pwsh
+        if: ${{ !cancelled() }}
 
-  # type-checkers:
-  #   runs-on: ubuntu-latest
-  #   timeout-minutes: *timeout-minutes
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #     - uses: astral-sh/setup-uv@v7
-  #       with:
-  #         python-version: ${{ matrix.python-version }}
-  #         activate-environment: true
-  #     - run: uv pip install --group=type-checkers
+  type-checkers:
+    runs-on: ubuntu-latest
+    timeout-minutes: *timeout-minutes
+    strategy:
+      fail-fast: false
+      matrix:
+        # python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
+        python-version: ["3.14"]
+    steps:
+      - uses: actions/checkout@v4
+      - uses: astral-sh/setup-uv@v7
+        with:
+          python-version: ${{ matrix.python-version }}
+          activate-environment: true
+      - run: uv pip install --group=type-checkers
 
-  #     - run: mypy . --python-version=${{ matrix.python-version }}
+      - run: mypy . --python-version=${{ matrix.python-version }}
 
-  #     - uses: jakebailey/pyright-action@v2
-  #       with:
-  #         python-version: ${{ matrix.python-version }}
-  #         version: PATH
-  #         annotate: errors
-  #       if: ${{ !cancelled() }} # Show issues even if the previous steps failed. But still fail the job
+      - uses: jakebailey/pyright-action@v2
+        with:
+          python-version: ${{ matrix.python-version }}
+          version: PATH
+          annotate: errors
+        if: ${{ !cancelled() }} # Show issues even if the previous steps failed. But still fail the job
