comment out unneeded tests

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -100,122 +100,122 @@ jobs:
           path: dist/*.whl
           if-no-files-found: error
 
-  # We cannot build and test on ARM64, so we cross-compile.
-  # Later, when available, we can add tests using this wheel on ARM64 VMs
-  build_arm64:
-    name: Cross-compile ARM
-    runs-on: windows-2019
-    timeout-minutes: 20
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: ["3.10", "3.11", "3.12", "3.13"]
-    steps:
-      - uses: actions/checkout@v4
+  # # We cannot build and test on ARM64, so we cross-compile.
+  # # Later, when available, we can add tests using this wheel on ARM64 VMs
+  # build_arm64:
+  #   name: Cross-compile ARM
+  #   runs-on: windows-2019
+  #   timeout-minutes: 20
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       python-version: ["3.10", "3.11", "3.12", "3.13"]
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v5
-        with:
-          python-version: ${{ matrix.python-version }}
-          architecture: "x64"
-          cache: pip
-          cache-dependency-path: .github/workflows/main.yml
-          check-latest: true
+  #     - name: Set up Python ${{ matrix.python-version }}
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: ${{ matrix.python-version }}
+  #         architecture: "x64"
+  #         cache: pip
+  #         cache-dependency-path: .github/workflows/main.yml
+  #         check-latest: true
 
-      - name: Setup Environment
-        run: |
-          python --version
-          pip --version
-          pip install --upgrade setuptools>=74 wheel build
+  #     - name: Setup Environment
+  #       run: |
+  #         python --version
+  #         pip --version
+  #         pip install --upgrade setuptools>=74 wheel build
 
-      - name: Obtain ARM64 library files
-        run: python .github\workflows\download-arm64-libs.py .\arm64libs
+  #     - name: Obtain ARM64 library files
+  #       run: python .github\workflows\download-arm64-libs.py .\arm64libs
 
-      - name: Build wheels
-        run: python -m build --wheel --config-setting=--build-option=build_ext --config-setting=--build-option=-L.\arm64libs --config-setting=--build-option=--plat-name=win-arm64 --config-setting=--build-option=build --config-setting=--build-option=--plat-name=win-arm64 --config-setting=--build-option=bdist_wheel --config-setting=--build-option=--plat-name=win-arm64
+  #     - name: Build wheels
+  #       run: python -m build --wheel --config-setting=--build-option=build_ext --config-setting=--build-option=-L.\arm64libs --config-setting=--build-option=--plat-name=win-arm64 --config-setting=--build-option=build --config-setting=--build-option=--plat-name=win-arm64 --config-setting=--build-option=bdist_wheel --config-setting=--build-option=--plat-name=win-arm64
 
-      - uses: actions/upload-artifact@v4
-        with:
-          name: artifacts-${{ matrix.python-version }}-arm64
-          path: dist/*.whl
-          if-no-files-found: error
+  #     - uses: actions/upload-artifact@v4
+  #       with:
+  #         name: artifacts-${{ matrix.python-version }}-arm64
+  #         path: dist/*.whl
+  #         if-no-files-found: error
 
-  merge:
-    runs-on: windows-latest
-    needs: [test, build_arm64]
-    steps:
-      - name: Merge Artifacts
-        uses: actions/upload-artifact/merge@v4
-        with:
-          name: artifacts
-          pattern: artifacts-*
-      - name: Delete standalone Artifacts
-        uses: geekyeggo/delete-artifact@v5
-        with:
-          name: artifacts-*
+  # merge:
+  #   runs-on: windows-latest
+  #   needs: [test, build_arm64]
+  #   steps:
+  #     - name: Merge Artifacts
+  #       uses: actions/upload-artifact/merge@v4
+  #       with:
+  #         name: artifacts
+  #         pattern: artifacts-*
+  #     - name: Delete standalone Artifacts
+  #       uses: geekyeggo/delete-artifact@v5
+  #       with:
+  #         name: artifacts-*
 
-  # This job can be run locally by running `pre-commit run`
-  checkers:
-    runs-on: windows-2019
-    timeout-minutes: 20
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-python@v5
-        with:
-          # This job only needs to target the oldest supported version
-          python-version: "3.8"
-          cache: pip
-          cache-dependency-path: .github/workflows/main.yml
-      - run: pip install clang-format==18.1.* pycln
-      - run: pycln . --config=pycln.toml --check
-      - uses: astral-sh/ruff-action@v3
-        with:
-          version: "0.8.4"
-      - run: ruff format --check
-      - run:
-          | # Too many files to fit in a single command, also exclude vendored Scintilla and MAPIStubLibrary
-          clang-format --Werror --dry-run $(git ls-files '*.cpp' ':!:com/win32comext/mapi/src/MAPIStubLibrary/')
-          if ($LastExitCode -ne 0) { exit $LastExitCode }
-          clang-format --Werror --dry-run $(git ls-files '*.h' ':!:Pythonwin/Scintilla/' ':!:com/win32comext/mapi/src/MAPIStubLibrary/')
-          if ($LastExitCode -ne 0) { exit $LastExitCode }
+  # # This job can be run locally by running `pre-commit run`
+  # checkers:
+  #   runs-on: windows-2019
+  #   timeout-minutes: 20
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: actions/setup-python@v5
+  #       with:
+  #         # This job only needs to target the oldest supported version
+  #         python-version: "3.8"
+  #         cache: pip
+  #         cache-dependency-path: .github/workflows/main.yml
+  #     - run: pip install clang-format==18.1.* pycln
+  #     - run: pycln . --config=pycln.toml --check
+  #     - uses: astral-sh/ruff-action@v3
+  #       with:
+  #         version: "0.8.4"
+  #     - run: ruff format --check
+  #     - run:
+  #         | # Too many files to fit in a single command, also exclude vendored Scintilla and MAPIStubLibrary
+  #         clang-format --Werror --dry-run $(git ls-files '*.cpp' ':!:com/win32comext/mapi/src/MAPIStubLibrary/')
+  #         if ($LastExitCode -ne 0) { exit $LastExitCode }
+  #         clang-format --Werror --dry-run $(git ls-files '*.h' ':!:Pythonwin/Scintilla/' ':!:com/win32comext/mapi/src/MAPIStubLibrary/')
+  #         if ($LastExitCode -ne 0) { exit $LastExitCode }
 
-  mypy:
-    runs-on: windows-2019
-    timeout-minutes: 20
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-python@v5
-        with:
-          python-version: ${{ matrix.python-version }}
-          cache: pip
-          cache-dependency-path: .github/workflows/main.yml
-          check-latest: true
-      - run: pip install types-setuptools PyOpenGL mypy[faster-cache]==1.14.*
-      - run: mypy . --python-version=${{ matrix.python-version }}
+  # mypy:
+  #   runs-on: windows-2019
+  #   timeout-minutes: 20
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: actions/setup-python@v5
+  #       with:
+  #         python-version: ${{ matrix.python-version }}
+  #         cache: pip
+  #         cache-dependency-path: .github/workflows/main.yml
+  #         check-latest: true
+  #     - run: pip install types-setuptools PyOpenGL mypy[faster-cache]==1.14.*
+  #     - run: mypy . --python-version=${{ matrix.python-version }}
 
-  pyright:
-    runs-on: windows-2019
-    timeout-minutes: 20
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-python@v5
-        with:
-          python-version: ${{ matrix.python-version }}
-          cache: pip
-          cache-dependency-path: .github/workflows/main.yml
-          check-latest: true
-      # pyright vendors typeshed, but let's make sure we have the most up to date stubs
-      - run: pip install types-setuptools PyOpenGL
-      - uses: jakebailey/pyright-action@v2
-        with:
-          python-version: ${{ matrix.python-version }}
-          version: "1.1.396"
-          annotate: errors
+  # pyright:
+  #   runs-on: windows-2019
+  #   timeout-minutes: 20
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: actions/setup-python@v5
+  #       with:
+  #         python-version: ${{ matrix.python-version }}
+  #         cache: pip
+  #         cache-dependency-path: .github/workflows/main.yml
+  #         check-latest: true
+  #     # pyright vendors typeshed, but let's make sure we have the most up to date stubs
+  #     - run: pip install types-setuptools PyOpenGL
+  #     - uses: jakebailey/pyright-action@v2
+  #       with:
+  #         python-version: ${{ matrix.python-version }}
+  #         version: "1.1.396"
+  #         annotate: errors
