test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,207 +22,197 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
-        architecture: [x64, x86]
+        # python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
+        # architecture: [x64, x86]
+
+        python-version: ["3.13"]
+        architecture: [x64]
 
     steps:
       - uses: actions/checkout@v4
 
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v5
-        with:
-          python-version: ${{ matrix.python-version }}
-          architecture: ${{ matrix.architecture }}
-          cache: pip
-          cache-dependency-path: .github/workflows/main.yml
-          check-latest: true
+      # - name: Set up Python ${{ matrix.python-version }}
+      #   uses: actions/setup-python@v5
+      #   with:
+      #     python-version: ${{ matrix.python-version }}
+      #     architecture: ${{ matrix.architecture }}
+      #     cache: pip
+      #     cache-dependency-path: .github/workflows/main.yml
+      #     check-latest: true
 
-      - name: Fix user Scripts missing from PATH
-        if: matrix.architecture == 'x86'
-        run: |
-          # Work around https://github.com/actions/setup-python/issues/1005
-          $ScriptsPath = python -c "import sysconfig,os; print(sysconfig.get_path('scripts', f'{os.name}_user'))"
-          echo $ScriptsPath
-          Add-Content $env:GITHUB_PATH $ScriptsPath
+      # - name: Fix user Scripts missing from PATH
+      #   if: matrix.architecture == 'x86'
+      #   run: |
+      #     # Work around https://github.com/actions/setup-python/issues/1005
+      #     $ScriptsPath = python -c "import sysconfig,os; print(sysconfig.get_path('scripts', f'{os.name}_user'))"
+      #     echo $ScriptsPath
+      #     Add-Content $env:GITHUB_PATH $ScriptsPath
 
-      - name: Build and install
-        run: pip install . -v --user
+      # - name: Build and install
+      #   run: pip install . -v --user
 
-      # This needs to happen *after* installing pywin32 since
-      # AutoDuck/py2d.py currently relies on runtime imports for introspection
-      # This isn't included in the wheel (TODO: could we?)
-      # and only serves as a PR test for the docs.yaml workflow
-      - name: Generate PyWin32.chm help file
-        run: python AutoDuck/make.py
+      # # This needs to happen *after* installing pywin32 since
+      # # AutoDuck/py2d.py currently relies on runtime imports for introspection
+      # # This isn't included in the wheel (TODO: could we?)
+      # # and only serves as a PR test for the docs.yaml workflow
+      # - name: Generate PyWin32.chm help file
+      #   run: python AutoDuck/make.py
 
-      # Smokescreen test to validate postinstall doesn't crash, dlls can be found, and both pathless invocation methods work
-      - name: Run postinstall install/remove
-        run: |
-          $UserSite = "$(python -m site --user-site)"
-          python -m win32.scripts.pywin32_postinstall -install -destination "$UserSite"
-          pywin32_postinstall -remove -destination "$UserSite"
+      # # Smokescreen test to validate postinstall doesn't crash, dlls can be found, and both pathless invocation methods work
+      # - name: Run postinstall install/remove
+      #   run: |
+      #     $UserSite = "$(python -m site --user-site)"
+      #     python -m win32.scripts.pywin32_postinstall -install -destination "$UserSite"
+      #     pywin32_postinstall -remove -destination "$UserSite"
 
       # Compilation and registration of the PyCOMTest server dll
-      - name: Set up MSVC
+      - name: Add msbuild to PATH
         uses: microsoft/setup-msbuild@v2
-
-      # See https://github.com/actions/runner-images/issues/9701
-      # Adapted from https://github.com/actions/runner-images/issues/9873#issuecomment-2139288682
-      - name: Install missing Visual Studio components
-        run: |
-          Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
-          $VsInstallPath = vswhere.exe -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
-          [string]$ComponentsToAdd = @(
-            "Microsoft.VisualStudio.Component.VC.14.29.16.11.ATL"
-          ) | ForEach-Object {"--add $_"}
-          $ArgumentList = ('modify', '--installPath', "`"$VsInstallPath`"", $ComponentsToAdd, '--quiet', '--norestart', '--nocache')
-          echo "vs_installer.exe $($ArgumentList -join ' ')"
-          # should be run twice for some reason
-          Start-Process -FilePath vs_installer.exe -ArgumentList $ArgumentList -Wait -PassThru -WindowStyle Hidden
-          Start-Process -FilePath vs_installer.exe -ArgumentList $ArgumentList -Wait -PassThru -WindowStyle Hidden
+        with:
+          vs-version: "[17,"
 
       - name: Build and register the PyCOMTest server dll
         run: |
           msbuild com/TestSources/PyCOMTest/PyCOMTest.sln -property:Configuration=Release
           regsvr32 com/TestSources/PyCOMTest/x64/Release/PyCOMTest.dll
 
-      - name: Run tests
-        # Run the tests directly from the source dir so support files (eg, .wav files etc)
-        # can be found - they aren't installed into the Python tree.
-        run: python win32/scripts/pywin32_testall.py -v -skip-adodbapi
+  #     - name: Run tests
+  #       # Run the tests directly from the source dir so support files (eg, .wav files etc)
+  #       # can be found - they aren't installed into the Python tree.
+  #       run: python win32/scripts/pywin32_testall.py -v -skip-adodbapi
 
-      - name: Build wheels
-        run: pip wheel . -v --wheel-dir=dist
+  #     - name: Build wheels
+  #       run: pip wheel . -v --wheel-dir=dist
 
-      - uses: actions/upload-artifact@v4
-        # Upload artifacts even if tests fail
-        if: ${{ always() }}
-        with:
-          name: artifacts-${{ matrix.python-version }}-${{ matrix.architecture }}
-          path: dist/*.whl
-          if-no-files-found: error
+  #     - uses: actions/upload-artifact@v4
+  #       # Upload artifacts even if tests fail
+  #       if: ${{ always() }}
+  #       with:
+  #         name: artifacts-${{ matrix.python-version }}-${{ matrix.architecture }}
+  #         path: dist/*.whl
+  #         if-no-files-found: error
 
-  # We cannot build and test on ARM64, so we cross-compile.
-  # Later, when available, we can add tests using this wheel on ARM64 VMs
-  build_arm64:
-    name: Cross-compile ARM
-    runs-on: windows-2022
-    timeout-minutes: 25
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: ["3.10", "3.11", "3.12", "3.13"]
-    steps:
-      - uses: actions/checkout@v4
+  # # We cannot build and test on ARM64, so we cross-compile.
+  # # Later, when available, we can add tests using this wheel on ARM64 VMs
+  # build_arm64:
+  #   name: Cross-compile ARM
+  #   runs-on: windows-2022
+  #   timeout-minutes: 25
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       python-version: ["3.10", "3.11", "3.12", "3.13"]
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v5
-        with:
-          python-version: ${{ matrix.python-version }}
-          architecture: "x64"
-          cache: pip
-          cache-dependency-path: .github/workflows/main.yml
-          check-latest: true
+  #     - name: Set up Python ${{ matrix.python-version }}
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: ${{ matrix.python-version }}
+  #         architecture: "x64"
+  #         cache: pip
+  #         cache-dependency-path: .github/workflows/main.yml
+  #         check-latest: true
 
-      - name: Install build module
-        run: pip install --upgrade  build
+  #     - name: Install build module
+  #       run: pip install --upgrade  build
 
-      - name: Obtain ARM64 library files
-        run: python .github\workflows\download-arm64-libs.py .\arm64libs
+  #     - name: Obtain ARM64 library files
+  #       run: python .github\workflows\download-arm64-libs.py .\arm64libs
 
-      - name: Build wheels
-        run: python -m build --wheel --config-setting=--build-option=build_ext --config-setting=--build-option=-L.\arm64libs --config-setting=--build-option=--plat-name=win-arm64 --config-setting=--build-option=build --config-setting=--build-option=--plat-name=win-arm64 --config-setting=--build-option=bdist_wheel --config-setting=--build-option=--plat-name=win-arm64
+  #     - name: Build wheels
+  #       run: python -m build --wheel --config-setting=--build-option=build_ext --config-setting=--build-option=-L.\arm64libs --config-setting=--build-option=--plat-name=win-arm64 --config-setting=--build-option=build --config-setting=--build-option=--plat-name=win-arm64 --config-setting=--build-option=bdist_wheel --config-setting=--build-option=--plat-name=win-arm64
 
-      - uses: actions/upload-artifact@v4
-        with:
-          name: artifacts-${{ matrix.python-version }}-arm64
-          path: dist/*.whl
-          if-no-files-found: error
+  #     - uses: actions/upload-artifact@v4
+  #       with:
+  #         name: artifacts-${{ matrix.python-version }}-arm64
+  #         path: dist/*.whl
+  #         if-no-files-found: error
 
-  merge:
-    runs-on: windows-latest
-    needs: [test, build_arm64]
-    steps:
-      - name: Merge Artifacts
-        uses: actions/upload-artifact/merge@v4
-        with:
-          name: artifacts
-          pattern: artifacts-*
-      - name: Delete standalone Artifacts
-        uses: geekyeggo/delete-artifact@v5
-        with:
-          name: artifacts-*
+  # merge:
+  #   runs-on: windows-latest
+  #   needs: [test, build_arm64]
+  #   steps:
+  #     - name: Merge Artifacts
+  #       uses: actions/upload-artifact/merge@v4
+  #       with:
+  #         name: artifacts
+  #         pattern: artifacts-*
+  #     - name: Delete standalone Artifacts
+  #       uses: geekyeggo/delete-artifact@v5
+  #       with:
+  #         name: artifacts-*
 
-  # This job can be run locally by running `pre-commit run`
-  checkers:
-    runs-on: windows-2022
-    timeout-minutes: 25
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-python@v5
-        with:
-          # This job only needs to target the oldest supported version
-          python-version: "3.8"
-          cache: pip
-          cache-dependency-path: .github/workflows/main.yml
-      - run: pip install clang-format==18.1.* pycln
-      # !cancelled(): Show issues even if the previous steps failed. But still fail the job
-      - run: pycln . --config=pycln.toml --check
-      - name: Run Ruff linter
-        uses: astral-sh/ruff-action@v3
-        with:
-          version: "0.11.0"
-        if: ${{ !cancelled() }}
-      - name: Run Ruff formatter
-        run: ruff format --check
-        if: ${{ !cancelled() }}
-      # Too many files to fit in a single command, also exclude vendored Scintilla and MAPIStubLibrary
-      - run: |
-          clang-format --Werror --dry-run $(git ls-files '*.cpp' ':!:com/win32comext/mapi/src/MAPIStubLibrary/')
-          if ($LastExitCode -ne 0) { exit $LastExitCode }
-        if: ${{ !cancelled() }}
-      - run: |
-          clang-format --Werror --dry-run $(git ls-files '*.h' ':!:Pythonwin/Scintilla/' ':!:com/win32comext/mapi/src/MAPIStubLibrary/')
-          if ($LastExitCode -ne 0) { exit $LastExitCode }
-        if: ${{ !cancelled() }}
+  # # This job can be run locally by running `pre-commit run`
+  # checkers:
+  #   runs-on: windows-2022
+  #   timeout-minutes: 25
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: actions/setup-python@v5
+  #       with:
+  #         # This job only needs to target the oldest supported version
+  #         python-version: "3.8"
+  #         cache: pip
+  #         cache-dependency-path: .github/workflows/main.yml
+  #     - run: pip install clang-format==18.1.* pycln
+  #     # !cancelled(): Show issues even if the previous steps failed. But still fail the job
+  #     - run: pycln . --config=pycln.toml --check
+  #     - name: Run Ruff linter
+  #       uses: astral-sh/ruff-action@v3
+  #       with:
+  #         version: "0.11.0"
+  #       if: ${{ !cancelled() }}
+  #     - name: Run Ruff formatter
+  #       run: ruff format --check
+  #       if: ${{ !cancelled() }}
+  #     # Too many files to fit in a single command, also exclude vendored Scintilla and MAPIStubLibrary
+  #     - run: |
+  #         clang-format --Werror --dry-run $(git ls-files '*.cpp' ':!:com/win32comext/mapi/src/MAPIStubLibrary/')
+  #         if ($LastExitCode -ne 0) { exit $LastExitCode }
+  #       if: ${{ !cancelled() }}
+  #     - run: |
+  #         clang-format --Werror --dry-run $(git ls-files '*.h' ':!:Pythonwin/Scintilla/' ':!:com/win32comext/mapi/src/MAPIStubLibrary/')
+  #         if ($LastExitCode -ne 0) { exit $LastExitCode }
+  #       if: ${{ !cancelled() }}
 
-  mypy:
-    runs-on: windows-2022
-    timeout-minutes: 25
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-python@v5
-        with:
-          python-version: ${{ matrix.python-version }}
-          cache: pip
-          cache-dependency-path: .github/workflows/main.yml
-          check-latest: true
-      - run: pip install types-setuptools PyOpenGL mypy[faster-cache]==1.14.*
-      - run: mypy . --python-version=${{ matrix.python-version }}
+  # mypy:
+  #   runs-on: windows-2022
+  #   timeout-minutes: 25
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: actions/setup-python@v5
+  #       with:
+  #         python-version: ${{ matrix.python-version }}
+  #         cache: pip
+  #         cache-dependency-path: .github/workflows/main.yml
+  #         check-latest: true
+  #     - run: pip install types-setuptools PyOpenGL mypy[faster-cache]==1.14.*
+  #     - run: mypy . --python-version=${{ matrix.python-version }}
 
-  pyright:
-    runs-on: windows-2022
-    timeout-minutes: 25
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-python@v5
-        with:
-          python-version: ${{ matrix.python-version }}
-          cache: pip
-          cache-dependency-path: .github/workflows/main.yml
-          check-latest: true
-      # pyright vendors typeshed, but let's make sure we have the most up to date stubs
-      - run: pip install types-setuptools PyOpenGL
-      - uses: jakebailey/pyright-action@v2
-        with:
-          python-version: ${{ matrix.python-version }}
-          version: "1.1.396"
-          annotate: errors
+  # pyright:
+  #   runs-on: windows-2022
+  #   timeout-minutes: 25
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: actions/setup-python@v5
+  #       with:
+  #         python-version: ${{ matrix.python-version }}
+  #         cache: pip
+  #         cache-dependency-path: .github/workflows/main.yml
+  #         check-latest: true
+  #     # pyright vendors typeshed, but let's make sure we have the most up to date stubs
+  #     - run: pip install types-setuptools PyOpenGL
+  #     - uses: jakebailey/pyright-action@v2
+  #       with:
+  #         python-version: ${{ matrix.python-version }}
+  #         version: "1.1.396"
+  #         annotate: errors
