test VS Component necessity

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -64,8 +64,8 @@ jobs:
       - name: Add msbuild to PATH
         uses: microsoft/setup-msbuild@v2
 
-      - name: Install missing Visual Studio components
-        run: python .github\workflows\install-vs-components.py
+      # - name: Install missing Visual Studio components
+      #   run: python .github\workflows\install-vs-components.py
 
       - name: Build and register the PyCOMTest server dll
         # Pass Silent flag to regsvr32 to avoid hanging on confirmation window
@@ -89,116 +89,116 @@ jobs:
 
   # We cannot build and test on ARM64, so we cross-compile.
   # Later, when available, we can add tests using this wheel on ARM64 VMs
-  build_arm64:
-    name: Cross-compile ARM
-    runs-on: windows-2022
-    timeout-minutes: 30
-    strategy:
-      fail-fast: false
-      matrix:
-        # pythonarm64 NuGet's has no download for Python ~=3.9.11
-        python-version: ["3.9.10", "3.10", "3.11", "3.12", "3.13", "3.14"]
-    steps:
-      - uses: actions/checkout@v4
+  # build_arm64:
+  #   name: Cross-compile ARM
+  #   runs-on: windows-2022
+  #   timeout-minutes: 30
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       # pythonarm64 NuGet's has no download for Python ~=3.9.11
+  #       python-version: ["3.9.10", "3.10", "3.11", "3.12", "3.13", "3.14"]
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v6
-        with:
-          python-version: ${{ matrix.python-version }}
-          architecture: x64
-          cache: pip
-          cache-dependency-path: .github/workflows/main.yml
-          check-latest: true
-          allow-prereleases: true
+  #     - name: Set up Python ${{ matrix.python-version }}
+  #       uses: actions/setup-python@v6
+  #       with:
+  #         python-version: ${{ matrix.python-version }}
+  #         architecture: x64
+  #         cache: pip
+  #         cache-dependency-path: .github/workflows/main.yml
+  #         check-latest: true
+  #         allow-prereleases: true
 
-      - name: Install build module
-        run: pip install --upgrade build
+  #     - name: Install build module
+  #       run: pip install --upgrade build
 
-      - name: Obtain ARM64 library files
-        run: python .github\workflows\download-arm64-libs.py ./arm64libs
+  #     - name: Obtain ARM64 library files
+  #       run: python .github\workflows\download-arm64-libs.py ./arm64libs
 
-      - name: Build wheels
-        run: python -m build --wheel --config-setting=--build-option="build_ext -L./arm64libs --plat-name=win-arm64 build --plat-name=win-arm64 bdist_wheel --plat-name=win-arm64"
+  #     - name: Build wheels
+  #       run: python -m build --wheel --config-setting=--build-option="build_ext -L./arm64libs --plat-name=win-arm64 build --plat-name=win-arm64 bdist_wheel --plat-name=win-arm64"
 
-      - uses: actions/upload-artifact@v4
-        with:
-          name: artifacts-${{ matrix.python-version }}-arm64
-          path: dist/*.whl
-          if-no-files-found: error
+  #     - uses: actions/upload-artifact@v4
+  #       with:
+  #         name: artifacts-${{ matrix.python-version }}-arm64
+  #         path: dist/*.whl
+  #         if-no-files-found: error
 
-  merge:
-    runs-on: ubuntu-latest
-    needs: [test, build_arm64]
-    steps:
-      - name: Merge Artifacts
-        uses: actions/upload-artifact/merge@v4
-        with:
-          name: artifacts
-          pattern: artifacts-*
-      - name: Delete standalone Artifacts
-        uses: geekyeggo/delete-artifact@v5
-        with:
-          name: artifacts-*
+  # merge:
+  #   runs-on: ubuntu-latest
+  #   needs: [test, build_arm64]
+  #   steps:
+  #     - name: Merge Artifacts
+  #       uses: actions/upload-artifact/merge@v4
+  #       with:
+  #         name: artifacts
+  #         pattern: artifacts-*
+  #     - name: Delete standalone Artifacts
+  #       uses: geekyeggo/delete-artifact@v5
+  #       with:
+  #         name: artifacts-*
 
-  # This job can be run locally by running `pre-commit run`
-  checkers:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-python@v6
-        with:
-          # This job only needs to target the oldest supported version
-          python-version: "3.9"
-          cache: pip
-          cache-dependency-path: .github/workflows/main.yml
-      - run: pip install --group=checkers
+  # # This job can be run locally by running `pre-commit run`
+  # checkers:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: actions/setup-python@v6
+  #       with:
+  #         # This job only needs to target the oldest supported version
+  #         python-version: "3.9"
+  #         cache: pip
+  #         cache-dependency-path: .github/workflows/main.yml
+  #     - run: pip install --group=checkers
 
-      # !cancelled(): Show issues even if the previous steps failed. But still fail the job
-      - run: pycln . --config=pycln.toml --check
+  #     # !cancelled(): Show issues even if the previous steps failed. But still fail the job
+  #     - run: pycln . --config=pycln.toml --check
 
-      - name: Run Ruff linter
-        uses: astral-sh/ruff-action@v3
-        if: ${{ !cancelled() }}
-      - name: Run Ruff formatter
-        run: ruff format --check
-        if: ${{ !cancelled() }}
+  #     - name: Run Ruff linter
+  #       uses: astral-sh/ruff-action@v3
+  #       if: ${{ !cancelled() }}
+  #     - name: Run Ruff formatter
+  #       run: ruff format --check
+  #       if: ${{ !cancelled() }}
 
-      # Too many files to fit in a single command, also exclude vendored Scintilla and MAPIStubLibrary
-      - run: |
-          clang-format --Werror --dry-run $(git ls-files '*.cpp' ':!:com/win32comext/mapi/src/MAPIStubLibrary/')
-          if ($LastExitCode -ne 0) { exit $LastExitCode }
-        shell: pwsh
-        if: ${{ !cancelled() }}
-      - run: |
-          clang-format --Werror --dry-run $(git ls-files '*.h' ':!:Pythonwin/Scintilla/' ':!:com/win32comext/mapi/src/MAPIStubLibrary/')
-          if ($LastExitCode -ne 0) { exit $LastExitCode }
-        shell: pwsh
-        if: ${{ !cancelled() }}
+  #     # Too many files to fit in a single command, also exclude vendored Scintilla and MAPIStubLibrary
+  #     - run: |
+  #         clang-format --Werror --dry-run $(git ls-files '*.cpp' ':!:com/win32comext/mapi/src/MAPIStubLibrary/')
+  #         if ($LastExitCode -ne 0) { exit $LastExitCode }
+  #       shell: pwsh
+  #       if: ${{ !cancelled() }}
+  #     - run: |
+  #         clang-format --Werror --dry-run $(git ls-files '*.h' ':!:Pythonwin/Scintilla/' ':!:com/win32comext/mapi/src/MAPIStubLibrary/')
+  #         if ($LastExitCode -ne 0) { exit $LastExitCode }
+  #       shell: pwsh
+  #       if: ${{ !cancelled() }}
 
-  type-checkers:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-python@v6
-        with:
-          python-version: ${{ matrix.python-version }}
-          cache: pip
-          cache-dependency-path: .github/workflows/main.yml
-          check-latest: true
-          allow-prereleases: true
-      - run: pip install --group=type-checkers
+  # type-checkers:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: actions/setup-python@v6
+  #       with:
+  #         python-version: ${{ matrix.python-version }}
+  #         cache: pip
+  #         cache-dependency-path: .github/workflows/main.yml
+  #         check-latest: true
+  #         allow-prereleases: true
+  #     - run: pip install --group=type-checkers
 
-      - run: mypy . --python-version=${{ matrix.python-version }}
+  #     - run: mypy . --python-version=${{ matrix.python-version }}
 
-      - uses: jakebailey/pyright-action@v2
-        with:
-          python-version: ${{ matrix.python-version }}
-          version: PATH
-          annotate: errors
-        if: ${{ !cancelled() }} # Show issues even if the previous steps failed. But still fail the job
+  #     - uses: jakebailey/pyright-action@v2
+  #       with:
+  #         python-version: ${{ matrix.python-version }}
+  #         version: PATH
+  #         annotate: errors
+  #       if: ${{ !cancelled() }} # Show issues even if the previous steps failed. But still fail the job
